package com.eb.imagelab.model;

public enum EnumGreyScale {
	

	GREY_SCALE_BT601,
	GREY_SCALE_BT709,
	GREY_SCALE_AVG,					
	GREY_SCALE_DESATURATION,	
	GREY_SCALE_DECOMPOSITION_MIN,	
	GREY_SCALE_DECOMPOSITION_MAX,	
	GREY_SCALE_RED_CHANNEL,		
	GREY_SCALE_GREEN_CHANNEL,		
	GREY_SCALE_BLUE_CHANNEL;			
}
